#!/usr/bin/env bash

function ci:compile {
  :
}

function ci:lint {
  lint:all || true
}

function ci:workflow-lint {
  :
}

function ci:security-check {
  :
}

function ci:test {
  :
}

function ci:static-analysis {
  :
}

function ci:secret-scan {
  :
}

function ci:acceptance-gate-bypass-check {
  :
}

function ci:acceptance-gate-bypass-check:test {
  :
}
