import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import Link from 'next/link'

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          Zane Riley is a product designer based in Tokyo
        </h1>

        <p className={styles.description}>
          Get started by editing{' '}
          <code className={styles.code}>pages/index.js</code>
        </p>
	
	<Link href="/case-studies/helping-people-find-healthcare">
		<a>Helping people find healthcare</a>
	</Link>
        
	<Link href="/case-studies/building-cohesive-products-through-design-ops">
		<a>Building cohesive products through design ops</a>
	</Link>

	<Link href="/case-studies/improving-an-ecommerce-flow">
		<a>Improving an ecommerce flow</a>
	</Link>
      </main>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{' '}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  )
}
