import fs from "node:fs";
import path from "node:path";
import {
  calculateSpaceScale,
  calculateTypeScale,
  generateSpaceCSSVariables,
  generateTypeCSSVariables,
} from "./fluid-type.ts";
import {
  latinTypeConfig,
  latinSpaceConfig,
  cjkTypeConfig,
  cjkSpaceConfig,
} from "./configs/type-config.ts";
import fontMetrics from "./font-metrics.json";

const OUTPUT_FILE = path.resolve("css/_typography.css");

// Helper to namespace variables
export function namespaceVariables(variables: string, namespace: string): string {
  return variables
    .split('\n')
    .map(line => {
      // Skip comments and empty lines
      if (line.trim().startsWith('/*') || line.trim() === '') return line;
      // Replace '--fs-' or '--space-' with '--{namespace}-fs-' or '--{namespace}-space-'
      return line.replace(/--(fs|space)-/g, `--${namespace}-$1-`);
    })
    .join('\n');
}

// Generate semantic variable mappings
export function generateSemanticVariables(script: string = 'latin'): string {
  const typeLabels = [
    "7xl", "6xl", "5xl", "4xl", "3xl", "2xl", "1xl", "md", "1xs", "2xs"
  ];
  const spaceLabels = ["4xl", "3xl", "2xl", "1xl", "md", "1xs", "2xs", "3xs"];

  const typeVars = typeLabels
    .map(label => `  --fs-${label}: var(--${script}-fs-${label});`)
    .join('\n');

  const spaceVars = spaceLabels
    .map(label => `  --space-${label}: var(--${script}-space-${label});`)
    .join('\n');

  return `${typeVars}\n\n${spaceVars}`;
}

// Generate CSS for font metrics
function generateFontMetricsCSS(): string {
  let css = "";
  for (const [font, metrics] of Object.entries(fontMetrics)) {
    css += `  --${font}-units-per-em: ${metrics.unitsPerEm};\n`;
    css += `  --${font}-cap-height: ${metrics.capHeight};\n`;
    css += `  --${font}-ascent: ${metrics.ascent};\n`;
    css += `  --${font}-descent: ${metrics.descent};\n`;
    css += `  --${font}-x-height: ${metrics.xHeight};\n`;
  }
  return css;
}

export function generateCSS(): string {
  // Generate and namespace variables
  const latinTypeVars = namespaceVariables(
    generateTypeCSSVariables(latinTypeConfig),
    'latin'
  );
  const latinSpaceVars = namespaceVariables(
    generateSpaceCSSVariables(latinSpaceConfig),
    'latin'
  );

  const cjkTypeVars = namespaceVariables(
    generateTypeCSSVariables(cjkTypeConfig),
    'cjk'
  );
  const cjkSpaceVars = namespaceVariables(
    generateSpaceCSSVariables(cjkSpaceConfig),
    'cjk'
  );

  // Generate semantic variables
  const semanticVars = generateSemanticVariables('latin');
  const semanticCJKVars = generateSemanticVariables('cjk');

  // Generate font metrics variables
  const fontMetricsVars = generateFontMetricsCSS();

  return `/* 
* DO NOT EDIT THIS FILE DIRECTLY. 
* Your changes will be overwritten. This file is auto-generated. 
* Generated on: ${new Date().toISOString()}
*/
  
:root {
  /* Latin Typography Variables */
${latinTypeVars}

  /* Latin Spacing Variables */
${latinSpaceVars}

  /* CJK Typography Variables */
${cjkTypeVars}

  /* CJK Spacing Variables */
${cjkSpaceVars}

  /* Font Metrics */
${fontMetricsVars}

  /* Semantic Variables (Default to Latin) */
${semanticVars}
}

/* CJK Overrides */
html[lang="ja"] {
  /* Semantic Variables (CJK) */
${semanticCJKVars}
}
`.trim();
}

// Custom error classes for better error handling
export class CSSGenerationError extends Error {
  constructor(message: string, public originalError?: Error) {
    super(message);
    this.name = 'CSSGenerationError';
  }
}

export class CSSWriteError extends Error {
  constructor(message: string, public originalError?: Error) {
    super(message);
    this.name = 'CSSWriteError';
  }
}

// Modified writeCSS function
export function writeCSS(css: string): void {
  try {
    fs.writeFileSync(OUTPUT_FILE, css);
    console.log(`Fluid CSS variables generated successfully at ${OUTPUT_FILE}`);
  } catch (error) {
    throw new CSSWriteError(
      `Failed to write CSS file to ${OUTPUT_FILE}`,
      error instanceof Error ? error : undefined
    );
  }
}

// Modified generateAndWriteCSS function
export function generateAndWriteCSS(): void {
  try {
    // Reference the module's own exports
    const css = exports.generateCSS();
    exports.writeCSS(css);
    console.log("CSS generation complete.");
  } catch (error) {
    if (error instanceof CSSWriteError) {
      console.error("An error occurred while writing CSS:", error);
      throw error;
    } else if (error instanceof CSSGenerationError) {
      console.error("An error occurred during CSS generation:", error);
      throw error;
    } else {
      const generationError = new CSSGenerationError(
        "An unexpected error occurred during CSS generation",
        error instanceof Error ? error : undefined
      );
      console.error("An unexpected error occurred during CSS generation:", generationError);
      throw generationError;
    }
  }
}

// Main execution
if (require.main === module) {
  try {
    generateAndWriteCSS();
  } catch (error) {
    console.error(error);
    process.exit(1);
  }
}

// Add the generateScales function
export function generateScales() {
  const latinTypeVars = generateTypeCSSVariables(latinTypeConfig);
  const latinSpaceVars = generateSpaceCSSVariables(latinSpaceConfig);
  const cjkTypeVars = generateTypeCSSVariables(cjkTypeConfig);
  const cjkSpaceVars = generateSpaceCSSVariables(cjkSpaceConfig);
  
  return {
    typeSizes: {
      ...latinTypeVars,
      ...cjkTypeVars,
    },
    spaceSizes: {
      ...latinSpaceVars,
      ...cjkSpaceVars,
    },
  };
}

