name: "CI"

on:
  pull_request:
    branches:
      - "*"
  push:
    branches:
      - "main"
      - "master"

jobs:
  test:
    runs-on: "ubuntu-22.04"

    steps:
      - uses: "actions/checkout@v2"

      - name: "Install CI dependencies"
        run: |
          ./run ci:install-deps

      - name: "Test"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GITHUB_EVENT_PATH: ${{ github.event_path }}
        run: |
          # Remove volumes in CI to avoid permission errors due to UID / GID.
          sed -i "s|.:/app|/tmp:/tmp|g" .env*
          sed -i "s|.:/app|/tmp:/tmp|g" docker-compose.yml
          ./run ci:test

      - name: DEBUG List directory contents
        run: |
          pwd
          ls -la
          
      # - name: Upload to Codecov
      #   env: 
      #     CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
      #   run: |
      #     curl -Os https://uploader.codecov.io/latest/linux/codecov
      #     chmod +x codecov
      #     ./codecov
      - name: Debug and Upload to Codecov
        env: 
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
        run: |
          echo "Current directory:"
          pwd
          echo "Directory contents:"
          ls -la
          echo "Searching for coverage files:"
          find . -name "*.json" -o -name "*.xml" -o -name "*.info"
          cd ../
          echo "Searching for coverage files in parent directory:"
          find . -name "*.json" -o -name "*.xml" -o -name "*.info"
          cd ../
          echo "Searching for coverage files in grandparent directory:"
          find . -name "*.json" -o -name "*.xml" -o -name "*.info"
          echo "Downloading Codecov uploader:"
          curl -Os https://uploader.codecov.io/latest/linux/codecov
          chmod +x codecov
          echo "Codecov uploader version:"
          ./codecov --version
          echo "Uploading to Codecov:"
          ./codecov -v
      - name: Debug coverage file
        run: |
          echo "Searching for excoveralls.json:"
          find . -name "excoveralls.json"
          if [ -f "excoveralls.json" ]; then
            echo "excoveralls.json found in current directory"
            cat excoveralls.json | head -n 10
          elif [ -f "code-coverage/excoveralls.json" ]; then
            echo "excoveralls.json found in code-coverage directory"
            cat code-coverage/excoveralls.json | head -n 10
          else
            echo "excoveralls.json not found, searching for other JSON files:"
            find . -name "*.json"
          fi